apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  namespace: default
data:
  config.yml: |
    services:
      - name: kubernetes
        url: https://kubernetes.default.svc

    bundles:
      kubernetes:
        service: kubernetes
        resource: opa/bundles/policies

    decision_logs:
      console: true

    default_decision: /kubernetes/admission
