apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: opa-validating-webhook
webhooks:
  - name: "validating-webhook.openpolicyagent.org"
    clientConfig:
      service:
        name: opa
        namespace: default
        path: "/v1/data/kubernetes/admission"
      caBundle: UEFTVEVfQ0FfQ0VSVF9IRVJF # You can use minikube CA for development
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
    failurePolicy: Ignore
    sideEffects: None  # This is the missing field
    admissionReviewVersions: ["v1"]
